version: '2'
services:
  sender:
    container_name: sender
    image: sendergo
    ports:
      - 8080:8080
    depends_on:
      - rabbit   
  consumer:
    container_name: consumer
    image: consumergo
    depends_on:
      - rabbit  
  rabbit:
    image: rabbitmq:3.6.7-management
    container_name: rabbit
    ports:
      - 15672:15672
      - 5672:5672
