version: '2'
services:
  client:
    container_name: client
    image: clientgo
    ports:
      - 8080:8080
    depends_on:
      - rabbit
    networks:
      - localnet     
  service:
    container_name: service
    image: servicego
    depends_on:
      - rabbit
    networks:
      - localnet  
  rabbit:
    image: rabbitmq:3.6.7-management
    container_name: rabbit
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - localnet
networks:
  localnet:   

